#ifndef __EXTRAE_VERSION_H__
#define __EXTRAE_VERSION_H__

#define EXTRAE_MAJOR 3
#define EXTRAE_MINOR 6
#define EXTRAE_MICRO 1

#define EXTRAE_STRINGIFY(x) EXTRAE_TO_STRING(x)
#define EXTRAE_TO_STRING(x) #x

#define EXTRAE_VERSION EXTRAE_STRINGIFY(EXTRAE_MAJOR) "." EXTRAE_STRINGIFY(EXTRAE_MINOR) "." EXTRAE_STRINGIFY(EXTRAE_MICRO)

#endif /* __EXTRAE_VERSION_H__ */
